language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - yarn build
deploy:
  fqdn: sulingliu.github.io
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  token: $liusuling
  keep_history: true
  on:
    branch: main